### PR TITLE
add missing cmake, signals, and a check for linux

### PR DESCRIPTION
**Pull request by patrickFuerst**

### CODE REVIEW

**Comment by patrickFuerst** [comment]
On Ubuntu it runs just sometimes on the CPU path. 
Mostly it crashes with an SIGSEGV on 	`memcpy( mBackVBuffer, mGstData.memoryMapInfo.data, mGstData.memoryMapInfo.size );
`
Need to look into it more.

**Comment by PetrosKataras** [comment]
I haven't tried the CPU path on Desktop Linux since these changes but I tried it on the Pi and I saw also the crash on the CPU path. On OS X it does not happen. I was planning to check on it once I wrap up the GL path on the Pi. 

On the other hand, I m able to run on Xubuntu 16.04 with gst 1.8.1 without issues the GL path. Be sure you have all plugins installed and enable `GST_DEBUG` to get more info.

**Comment by patrickFuerst** [comment]
Hey Petros, 

looking into the GL path problem, it looks like the linux kernel 4.4 was the problem. 
After upgrade the kernel to 4.6 it worked so far. 

Should a create a new PR  ?

**Comment by PetrosKataras** [comment]
I would suggest to let this sink a bit before starting tackling other issues. I would say lets test it well, see what works/what not from what is there already and once we have an overview we can decide further steps. Right now everything is very much in flux and there are some RPi updates that I haven't pushed yet so it can get pretty easily messy if we start opening different fronts :) 

Lets try to get an overview through testing and then we can organize our workflow better!

Thanks!

**Comment by PetrosKataras** [comment]
The CPU crasher is fixed in current HEAD. Its was a misplacement during the refactor.

**Comment by patrickFuerst** [comment]
Hey Petros, 

sounds fair enough :) 
Let's see how it's working with the PI for me.

**Pull request closed without merging**
